### ISSUE TITLE
List S3 objects not actually returning results

### ISSUE THREAD

**Issue by anonmily** [dxdc/aws-sdk-google-apps#19]
It seems like List S3 objects is not actually returning any results
<img width="1142" alt="image" src="https://github.com/dxdc/aws-sdk-google-apps/assets/8203544/1dab9102-0942-478e-bafe-79aa84ec343b">

**Comment by dxdc** [comment]
The AWS SDK appears to be returning data, so your issue is likely with: AWS permissions on your IAM user, region specific settings (in your init), specific params of how you are calling the SDK, or a mistake in your syntax.

For example, your prefix should likely be `360/` not `/360/`.

Please review the suggestions, and if you still have issues, test your use case from the cli with the [AWS JS SDK](https://github.com/aws/aws-sdk-js/tree/master) and confirm you get a different result. If so, please feel free to re-open this issue.

**Comment by anonmily** [comment]
@dxdc  Seems like that was the issue-- "360/" works but not "/360/". Thank you :)
